#!/bin/bash

macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_QCD_3.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_QCD_4.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_QCD_5.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_QCD.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_QCD_3.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_QCD_4.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_QCD_5.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_QCD.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_QCD_3.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_QCD_4.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_QCD_5.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_QCD.root

macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_Top_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_Top_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_Top_2.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_Top.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_Top_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_Top_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_Top_2.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_Top.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_Top_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_Top_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_Top_2.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_Top.root

macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_WJets_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_WJets_2.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_WJets_3.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_WJets.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_WJets_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_WJets_2.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_WJets_3.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_WJets.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_WJets_1.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_WJets_2.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_WJets_3.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_WJets.root

macroRun -m configs/macros/MergeAndCollectStacks.json -i SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_QCD.root -i SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_QCD.root -i SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_QCD.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_161718_bkgs_QCD.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_Top.root -i SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_Top.root -i SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_Top.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_161718_bkgs_Top.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_WJets.root -i SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_WJets.root -i SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_WJets.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_161718_bkgs_WJets.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_bkgs_ZJets.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_bkgs_ZJets.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_bkgs_ZJets.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_161718_bkgs_ZJets.root
macroRun -m configs/macros/MergeAndCollectStacks.json -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2016_signal_aEM_main.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2017_signal_aEM_main.root -i ${rprefx}/SR_dxy_study_DxyNmatch_SR_dxy_study_2018_signal_aEM_main.root -o SR_dxy_study_DxyNmatch_SR_dxy_study_161718_signal_aEM_main.root

xrdcp SR_dxy_*.root ${prefx}
